services:
  app:
    image: cosmtrek/air
    working_dir: /go/src/github.com/rexonms/kalomaya/
    volumes:
      - ./server:/go/src/github.com/rexonms/kalomaya/
    ports:
      - '8080:8080'

  react:
    build:
      context: ./client/
      dockerfile: ./dev.Dockerfile
    volumes:
      - ./client:/app
    ports:
      - '3000:3000'
